version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports:
      - "8081:8080"
    volumes:
      - /home/ubuntu/jenkins_home:/var/jenkins_home
    networks:
      - net
  remote_host:
    container_name: remote-host
    image: remote-host
    build:
      context: centos7
    networks:
      - net
    volumes:
      - /home/ubuntu/aws-bd-script1.sh:/tmp/script.sh    
  db_host:
    container_name: db
    image: mysql:5.7
    environment:  
      - "MYSQL_ROOT_PASSWORD=1234"
    volumes:
      - /home/ubuntu/db_data:/var/lib/mysql      
    networks:
      - net
networks:
  net:
